### ISSUE TITLE
[SUGGESTION] Add the option to trim recordings

### ISSUE THREAD

**Issue by AndreiMiculita** [Sav22999/common-voice-android#102]
It would be useful if voice samples could be trimmed after recording. If someone is recording, they wouldn't have to worry as much about speaking or pressing the stop button at the right moment.

**Comment by Sav22999** [comment]
@AndreiMiculita really thanks for the suggestion. I think this could be a good idea but a bit useless... basically I should implement a feature which will be cause a bigger size of the app... I would like having the app light, otherwise it will lose the advantage between the website.
For this reason, for now, I close this issue and label it as "Invalid" 😄 please, feel free to suggest other features eventually.
