### ISSUE TITLE
How to log in through email?

### ISSUE THREAD

**Issue by CrushedPixl** [Sav22999/common-voice-android#110]
To log into my Common Voice account I usually enter my email, and then authorize the browser by going to the emailed link. I can get the email when signing in from the app, but since I can't paste the link in the in-app browser I can't proceed. What should I do?

**Comment by Sav22999** [comment]
@CrushedPixl The app is able to open the verification link. So, if you tap on that link, Android should ask to you how to open it, and you should choose "CV Android". If the choosing doesn't appear, maybe it's because you set a browser as "default browser", so please remove (temporarly) that option.

Let me know updates 😄

**Comment by CrushedPixl** [comment]
That worked. My browser wasn't set to auto-open links in settings but did it anyway. Once I uninstalled it temporarily I got the prompt. Thanks!

Is it relevant to add an option to manually paste the link in case there is a default browser set?

**Comment by Sav22999** [comment]
It's in the future plans, but the development now is paused because I'm waiting news from Mozilla
