### ISSUE TITLE
[BUG] Daily Goal prompts when I am recording a sentence

### ISSUE THREAD

**Issue by dag7dev** [Sav22999/common-voice-android#129]
_Android (OS) version:_ 10
_Android (OS) language (in English):_ Italian
_App release:_ 2.2b
_App language (in English):_ Italian
_Device RAM:_ ?
_Device display size (in Inches):_ ?
_From what store have you installed the app?:_  GitHub
_Are there installed Google Services on your device?_ Yes 

**Description bug**
As title, Daily Goal modal window prompt when I have reached the goal and at the same time when I am recording a sentence 

**How to reproduce the bug**
1. Set daily goal
2. Reach Daily Goal when you are recording something

**Comment by Sav22999** [comment]
After many discussions with the other developers we decided to mark this issue as "wontfix" because it's not properly a bug, because the usability of the app is not corrupted and also because an implementation of a solution would be too complicated for this issue. So, because we adopt always the KISS principle, it's not necessary for the app (not now, at least).

Thanks anyway for the feedback.
