### ISSUE TITLE
[SUGGESTION] Only ask for microphone permission when recording

### ISSUE THREAD

**Issue by linsui** [Sav22999/common-voice-android#21]
**Description feedback/suggestion**
Microphone and storage permission is not needed when users only use listen function.

**Draft expected**
Only ask for microphone permission when users try to record.

**Additional context**

**Comment by Sav22999** [comment]
That's true, but in future there will be (i hope) the "Speak" section

**Comment by Sav22999** [comment]
Microphone permission permits to record the sentence, and Storage permits to save that recording.

**Comment by linsui** [comment]
Not all users need to use the Speak function. Some users only want to listen.

**Comment by Sav22999** [comment]
Oh ok, I'll add this suggestion. Thank you.

**Comment by Sav22999** [comment]
@linsui I'm implemented this feature in 0.0.19b:
- In first-run tutorial (general) you can skip permission (just tap on "Skip" below "Permit"/"Try again" button)
- In the Speak section (now it's not available) are asked otherwise you cannot use it

I close this issue because of I solved it 😄  thanks again to the suggestion!

**Comment by linsui** [comment]
Thanks!
